### ISSUE TITLE
[tgoe-godot] Godot 4 Tutorial

### ISSUE THREAD

**Issue by arantebw** [arantebw/reoasteroids#4]
YouTube Playlist: https://youtube.com/playlist?list=PL4cUxeGkcC9iHCXBpxbdsOByZ55Ez4bgF&si=X8xa3oYcYuNX_pli

## Episodes

- [x] arantebw/space-shooter#3
- [x] arantebw/space-shooter#2
- [x] #5
- [x] #7
- [x] #9
- [x] #11
- [x] #13
- [x] #15
- [x] #17
- [x] #19

## To-dos

- [x] prepare the starfigher assets
